name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build-docker:

    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get package version
        run: |
          echo "package_version=$(cat ./VERSION)" >> $GITHUB_ENV

      - name: Setup Buildx action
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.package_version }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:${{ env.package_version }}
          cache-to: type=inline
