name: build

on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
    branches:
      - master

jobs:

  build-docker:

    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name:
        run: |
          df -h
          du -sh /usr/local/lib/android
          du -sh /usr/share/dotnet

      # - name: Get package version
      #   run: |
      #     echo "version=$(cat ./VERSION)" >> $GITHUB_ENV

      # - name: Setup Buildx action
      #   uses: docker/setup-buildx-action@v1

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1 
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: ${{ startsWith(github.ref, 'refs/tags') }}
      #     tags: ghcr.io/${{ github.repository }}:${{ env.version }},ghcr.io/${{ github.repository }}:latest
      #     cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:latest
      #     cache-to: type=inline
